// App
export const SET_MOVIES_SORT_BY = "APP/SET_MOVIES_SORT_BY";

// Movies
export const REQUEST_MOVIES_SUCCESS = "MOVIES/REQUEST_MOVIES_SUCCESS";
export const REQUEST_MOVIES_ERROR = "MOVIES/REQUEST_MOVIES_ERROR";
// export const REQUEST_MOVIES_INIT = "MOVIES/REQUEST_MOVIES_INIT"; // To add a spinner while loading

// Genres
export const MAKE_GENRES = "GENRES/MAKE_GENRES";

// Modals
export const UPDATE_MODAL_VALUE_FIELD = "MODALS/UPDATE_MODAL_VALUE_FIELD";
export const RESET_MODAL_VALUES = "MODALS/RESET_MODAL_VALUES";
export const SET_MODAL_VALUES_FOR_EDIT = "MODALS/SET_MODAL_VALUES_FOR_EDIT";
