// App
export const SET_MOVIES_SORT_BY = "APP/SET_MOVIES_SORT_BY";

// Movies
export const REQUEST_MOVIES_SUCCESS = "MOVIES/REQUEST_MOVIES_SUCCESS";
export const REQUEST_MOVIES_ERROR = "MOVIES/REQUEST_MOVIES_ERROR";
// export const REQUEST_MOVIES_INIT = "MOVIES/REQUEST_MOVIES_INIT"; // To add a spinner while loading

// Modals
export const SET_MODAL_VALUES = "MODALS/SET_MODAL_VALUES";
