// App
export const SET_MOVIES_SORT_BY = "APP/SET_MOVIES_SORT_BY";
export const ALERT_SHOW = "APP/ALERT_SHOW";
export const ALERT_HIDE = "APP/ALERT_HIDE";
export const CHANGE_SEARCH_VALUE = "APP/CHANGE_SEARCH_VALUE";

// Movies
export const REQUEST_MOVIES_SUCCESS = "MOVIES/REQUEST_MOVIES_SUCCESS";
export const REQUEST_MOVIES_ERROR = "MOVIES/REQUEST_MOVIES_ERROR";
export const CLEAR_REQUEST_RESULT = "MOVIES/CLEAR_REQUEST_RESULT";

// Modals
export const SET_MODAL_VALUES = "MODALS/SET_MODAL_VALUES";
